# ISO Configuration for Aurora-Hyprland
# This creates a bootable ISO that will switch to your custom Aurora image after installation

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone" 
]

[customizations.installer.kickstart]
contents = """
%post
# Switch to your locally built Aurora-Hyprland image after installation
bootc switch --mutate-in-place --transport registry localhost/yourimage:latest
%end
"""
